name: ez_either
description: An easy approach of two types returning for Dart.
version: 0.0.3
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"


dev_dependencies:
  test: any


repository:
  https://github.com/viniciusamelio/ez_either

home:
  https://github.com/viniciusamelio/ez_either
